modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="flymod"
version="1.0"
displayName="Fly Mod"
authors="Yulia"
description='''
    Простой мод на полет по команде /fly.
    '''

[[dependencies.flymod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.flymod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"